### Variable definitions
@baseUrl = https://shjfowznkd.execute-api.us-east-1.amazonaws.com
@contentType = application/json

### Get all spaces
# @name getAllSpaces
GET {{baseUrl}}/prod/spaces


### Create a new space
# @name createSpace
POST {{baseUrl}}/prod/spaces
content-type: {{ contentType }}

 {
    "location": "Paris"
 }


### Set the id
 @id = {{ createSpace.response.body.id }}


### Get a space by ID
# @name getSpaceById
GET {{baseUrl}}/prod/spaces?id={{id}}

### Update a space by ID
# @name updateSpace
PUT {{baseUrl}}/prod/spaces?id={{id}}
content-type: {{ contentType }}

 {
    "location": "Paris2"
 }

### Delete a space by ID
# @name deleteSpace
DELETE {{baseUrl}}/prod/spaces?id={{id}}

