### Variable definitions
@url = https://shjfowznkd.execute-api.us-east-1.amazonaws.com/prod
@contentType = application/json
@token = ey

### Get all spaces
# @name getAllSpaces
GET {{url}}/spaces
Authorization: {{token}}


### Create a new space
# @name createSpace
POST {{url}}/spaces
content-type: {{ contentType }}
Authorization: {{token}}
 {
    "location": "Paris"
 }


### Set the id
 @id = {{ createSpace.response.body.id }}


### Get a space by ID
# @name getSpaceById
GET {{url}}/spaces?id={{id}}
Authorization: {{token}}

### Update a space by ID
# @name updateSpace
PUT {{url}}/spaces?id={{id}}
content-type: {{ contentType }}
Authorization: {{token}}
 {
    "location": "Paris2"
 }

### Delete a space by ID
# @name deleteSpace
DELETE {{url}}/spaces?id={{id}}
Authorization: {{token}}
