### 
GET https://shjfowznkd.execute-api.us-east-1.amazonaws.com/prod/spaces

### POST
POST https://shjfowznkd.execute-api.us-east-1.amazonaws.com/prod/spaces
content-type: application/json

 {
    "location": "Paris"
 }
###